src/Entity/Phone.php
<?php

namespace App\Entity;

use App\Repository\PhoneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PhoneRepository::class)
 */
class Phone
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $PhoneName;

    /**
     * @ORM\ManyToOne(targetEntity=Publisher::class, inversedBy="phones")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Publisher;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $OperatingSystem;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Memory;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $RAM;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $Dimension;

    /**
     * @ORM\Column(type="float")
     */
    private $Price;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;


    public function __construct()
    {
        $this->Quantity = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPhoneName(): ?string
    {
        return $this->PhoneName;
    }

    public function setPhoneName(string $PhoneName): self
    {
        $this->PhoneName = $PhoneName;

        return $this;
    }

    public function getPublisher(): ?Publisher
    {
        return $this->Publisher;
    }

    public function setPublisher(?Publisher $Publisher): self
    {
        $this->Publisher = $Publisher;

        return $this;
    }

    public function getOperatingSystem(): ?string
    {
        return $this->OperatingSystem;
    }

    public function setOperatingSystem(string $OperatingSystem): self
    {
        $this->OperatingSystem = $OperatingSystem;

        return $this;
    }

    public function getMemory(): ?string
    {
        return $this->Memory;
    }

    public function setMemory(string $Memory): self
    {
        $this->Memory = $Memory;

        return $this;
    }

    public function getRAM(): ?string
    {
        return $this->RAM;
    }

    public function setRAM(string $RAM): self
    {
        $this->RAM = $RAM;

        return $this;
    }

    public function getDimension(): ?string
    {
        return $this->Dimension;
    }

    public function setDimension(string $Dimension): self
    {
        $this->Dimension = $Dimension;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getGuestName(): Collection
    {
        return $this->GuestName;
    }

    public function addGuestName(Order $guestname): self
    {
        if (!$this->GuestName->contains($guestname)) {
            $this->GuestName[] = $guestname;
            $guestname->addPhone($this);
        }

        return $this;
    }

    public function removeGuestName(Order $guestname): self
    {
        if ($this->GuestName->removeElement($guestname)) {
            $guestname->removePhone($this);
        }

        return $this;
    }
    public function __toString() {
        return $this->PhoneName;
    }

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image)
    {
        if ($Image != null) {
            $this->Image = $Image;
        }

        return $this;
    }
}

src/Form/PhoneType.php
<?php

namespace App\Form;

use App\Entity\Phone;
use App\Entity\Publisher;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PhoneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('PhoneName')
            ->add('OperatingSystem')
            ->add('Memory', IntegerType::class)
            ->add('RAM', IntegerType::class)
            ->add('Dimension')
            ->add('Price', MoneyType::class,
            [
                'currency' => 'VND'
            ])
            ->add('Publisher', EntityType::class, [
            'class' => Publisher::class,
            'choice_label' => "CompanyName",
            ])
            -> add('Image', FileType::class,
            [
                'label' => 'Phone Image',
                'data_class' => null,
                'required' => is_null($builder->getData()->getImage())
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Phone::class,
        ]);
    }
}

src/Controller/PhoneController.php
<?php

namespace App\Controller;

use App\Entity\Phone;
use App\Entity\Publisher;
use App\Form\PublisherType;
use App\Form\PhoneType;
use PhpParser\Node\Expr\FuncCall;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

use function PHPUnit\Framework\throwException;

class PhoneController extends AbstractController
{
     /**
     * @Route("/phone", name="phone_list")
     */
    public function listPhone () {
        $phones = $this->getDoctrine()
                       ->getRepository(Phone::class)
                       ->findAll();
    
        return $this->render(
                        "phone/index.html.twig",
                        [
                            'phones' => $phones
                        ]
                     );
    }

    /**
     * @Route("/phone/detail/{id}", name="phone_detail")
     */
    public function detailPhone ($id) {
        $phone = $this->getDoctrine()
                       ->getRepository(Phone::class)
                       ->find($id);

        if ($phone == null) {
            $this->addFlash("Error", "Phone ID in invalid");
            return $this->redirectToRoute("phone_list");
        }

        return $this->render(
                        "phone/detail.html.twig",
                        [
                          'phone' => $phone
                        ]
        );
    }

    
    /**
     * @Route("/phone/delete/{id}", name="phone_delete")
     */
    public function deletePhone ($id)
    {
        $phone = $this->getDoctrine()
                          ->getRepository(Phone::class)
                          ->find($id);
        if($phone == null) {
            $this->addFlash("Error", "Invalid Phone ID");
            return $this->redirectToRoute("phone_list");
        }
        $manager = $this->getDoctrine()
                        ->getManager();
        $manager->remove($phone);
        $manager->flush();
        $this->addFlash("Info", "Phone has been deleted");    
        return $this->redirectToRoute("phone_list");
    }

    /**
     * @Route("/phone/create", name="phone_create")
     */
    public function createPhone (Request $request)
    {
        $phone = new Phone();
        $form = $this->createForm(PhoneType::class,$phone);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $image = $phone->getImage();
            $fileName=md5(uniqid());
            $fileExtension = $image->guessExtension();

            $imageName = $fileName . '.' . $fileExtension;

            try {
                $image->move(
                    $this->getParameter('phone_image'), $imageName
                );
            }
            catch (FileException $e)
            {
                throwException($e);
            }

            $phone->setImage($imageName);
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($phone);
            $manager->flush();

            

            $this->addFlash("Info", "Phone has been added!");
            return $this->redirectToRoute("phone_list");
        }
        return $this->render(
            "phone/create.html.twig",
            [
                "form" => $form->createView()
            ]
        );
    }

    /**
     * @Route("/phone/update/{id}", name="phone_update")
     */
    public function updatePhone (Request $request, $id)
    {
        $phone = $this->getDoctrine()
                          ->getRepository(Phone::class)
                          ->find($id);
        $form = $this->createForm(PhoneType::class,$phone);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $uploadedFile = $form['Image'] -> getData();
            if ($uploadedFile != null)
            {
                $image = $phone->getImage();
                $fileName = md5(uniqid());
                $fileExtension = $image->guessExtension();
                $imageName = $fileName . '.' . $fileExtension;
                try {
                    $image->move(
                        $this->getParameter('phone_image'), $imageName
                    );
                } catch (FileException $e) {
                    throwException($e);
                }
                $phone->setImage($imageName);
            }
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($phone);
            $manager->flush();

            $this->addFlash("Info", "Phone has been updated!");
            return $this->redirectToRoute("phone_detail", ['id' => $id]);
        }
        return $this->render(
            "phone/update.html.twig",
            [
                'form' => $form->createView(),
            ]
        );

    }


   
}

templates/phone/create.html.twig
{% extends "base.html.twig" %}
{% block title %} Add a new Phone {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Add Phone </h2>
        <div class="col-md-8">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.PhoneName) }}
                    {{ form_widget (form.PhoneName, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Publisher) }}
                    {{ form_widget (form.Publisher, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.OperatingSystem) }}
                    {{ form_widget (form.OperatingSystem, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Memory) }}
                    {{ form_widget (form.Memory, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.RAM) }}
                    {{ form_widget (form.RAM, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Dimension) }}
                    {{ form_widget (form.Dimension, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Price) }}
                    {{ form_widget (form.Price, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                  {{ form_label (form.Image) }}
                  {{ form_widget (form.Image, {'attr': {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group text-center mt-3">
                    <button class="btn btn-success">Create</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}

templates/phone/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone Detail{% endblock %}

{% block body %}

<div class="container mt-3">
    <br>
    <table class = "table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Phone ID</th>
                <th scope="col">Phone Name</th>
                <th scope="col">Publisher</th>
                <th scope="col">Operating System</th>
                <th scope="col">Memory</th>
                <th scope="col">RAM</th>
                <th scope="col">Dimension</th>
                <th scope="col">Phone Image</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row">{{ phone.id}}</td>
                <td scope="row">{{ phone.phonename}}</td>
                <td scope="row"><a href="{{ path('publisher_detail', {'id': phone.publisher.id} )}}">{{phone.publisher}}</a></td>
                <td scope="row">{{ phone.operatingsystem}}</td>
                <td scope="row">{{ phone.memory}}</td>
                <td scope="row">{{ phone.ram}}</td>
                <td scope="row">{{ phone.dimension}}</td>   
                <td scope="row">
                    {% if phone.image != null %}
                        <img src="{{ asset ('images/products/' ~ phone.image) }}" width="100px" height="120px">
                    {% else %}
                        <img src="{{ asset ('images/products/mobile.png') }}" width="100px" height="120px">
                    {% endif %}  </td>            
                <td scope="row">
                    <a class="btn btn-success" href="{{ path('phone_update', {'id': phone.id} )}}">Update</a>
                    <a class="btn btn-success" href="{{ path ('phone_delete', {'id': phone.id}) }}"onclick="return confirm('This publisher will be deleted!')">Delete</a>
            </tr>
        </tbody>
</div>
{% endblock %}

templates/phone/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone Information{% endblock %}

{% block body %}

<div class="container mt-3">
    {% for flash in app.flashes("Info") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Error") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>
<div class="container-fluid">
<a class="btn btn-success" href="{{ path ( 'phone_create' ) }}">Add New Phone</a>
<table class = "table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">Phone ID</th>
            <th scope="col">Phone Name</th>
            <th scope="col">Publisher</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for phone in phones %}
        <tr>
            <td scope="row">{{ phone.id}}</td>
            <td scope="row">{{ phone.phonename}}</td>
            <td scope="row">{{ phone.publisher}}</td>
            <td scope="row">
                <a class="btn btn-success" href="{{ path('phone_detail', {'id': phone.id} )}}">Detail</a>
                <a class="btn btn-success" href="{{ path('phone_update', {'id': phone.id} )}}">Update</a>
                <a class="btn btn-success" href="{{ path('phone_delete', {'id': phone.id} )}}"
                onclick="return confirm('This publisher will be deleted!')">Delete</a>
        </tr>
    </tbody>
    {% endfor %}
</div>
{% endblock %}

templates/phone/update.html.twig
{% extends "base.html.twig" %}
{% block title %} Update a Phone {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Update Phone </h2>
        <div class="col-md-5">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.PhoneName) }}
                    {{ form_widget (form.PhoneName, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Publisher) }}
                    {{ form_widget (form.Publisher, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.OperatingSystem) }}
                    {{ form_widget (form.OperatingSystem, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Memory) }}
                    {{ form_widget (form.Memory, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.RAM) }}
                    {{ form_widget (form.RAM, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Dimension) }}
                    {{ form_widget (form.Dimension, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Price) }}
                    {{ form_widget (form.Price, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                  {{ form_label (form.Image) }}
                  {{ form_widget (form.Image, {'attr': {'class' : 'form-control'}}) }}
                </div>
                <div class="form-group text-center mt-3">
                    <button class="btn btn-success">Update</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}