src/Entity/Publisher.php
<?php

namespace App\Entity;

use App\Repository\PublisherRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PublisherRepository::class)
 */
class Publisher
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $CompanyName;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $Country;

    /**
     * @ORM\OneToMany(targetEntity=Phone::class, mappedBy="Publisher")
     */
    private $phones;

    /**
     * @ORM\Column(type="integer")
     */
    private $Founded;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Image;

    public function __construct()
    {
        $this->phones = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCompanyName(): ?string
    {
        return $this->CompanyName;
    }

    public function setCompanyName(string $CompanyName): self
    {
        $this->CompanyName = $CompanyName;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }

    /**
     * @return Collection|Phone[]
     */
    public function getPhones(): Collection
    {
        return $this->phones;
    }

    public function addPhone(Phone $phone): self
    {
        if (!$this->phones->contains($phone)) {
            $this->phones[] = $phone;
            $phone->setPublisher($this);
        }

        return $this;
    }

    public function removePhone(Phone $phone): self
    {
        if ($this->phones->removeElement($phone)) {
            // set the owning side to null (unless already changed)
            if ($phone->getPublisher() === $this) {
                $phone->setPublisher(null);
            }
        }

        return $this;
    }

    public function getFounded(): ?int
    {
        return $this->Founded;
    }

    public function setFounded(int $Founded): self
    {
        $this->Founded = $Founded;

        return $this;
    }
    public function __toString() {
        return $this->CompanyName;
    }

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image): self
    {
        $this->Image = $Image;

        return $this;
    }
}

src/Form/PublisherType.php
<?php

namespace App\Form;

use App\Entity\Publisher;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PublisherType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('CompanyName')
            ->add('Country')
            // ->add('Quantity', EntityType::class, [
            //     'class' => Phone::class
            //     'Cho'
            // ])
            ->add('Image', FileType::class,
            [
                'label' => 'Publisher Image',
                'data_class' => null,
                'required' => is_null($builder->getData()->getImage())
            ])
            ->add('Founded')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Publisher::class,
        ]);
    }
}

src/Controller/PublisherController.php
<?php

namespace App\Controller;

use App\Entity\Phone;
use App\Entity\Publisher;
use App\Form\PublisherType;
use PhpParser\Node\Expr\FuncCall;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

use function PHPUnit\Framework\throwException;

class PublisherController extends AbstractController
{
    /**
     * @Route("/publisher", name="publisher_list")
     */
    public function listPublisher () {
        $publishers = $this->getDoctrine()
                              ->getRepository(Publisher::class)
                              ->findAll();
        return $this->render(
                        "publisher/index.html.twig",
                        [
                            'publishers' => $publishers,
                        ]
                     );
    }

    /**
     * @Route("/publisher/detail/{id}", name="publisher_detail")
     */
    public function detailPublisher ($id) {
        $publisher = $this->getDoctrine()
                       ->getRepository(Publisher::class)
                       ->find($id);

        if ($publisher == null) {
            $this->addFlash("Error", "Publisher ID in invalid");
            return $this->redirectToRoute("publisher_list");
        }

        return $this->render(
                        "publisher/detail.html.twig",
                        [
                          'publisher' => $publisher,
                        ]
        );
    }

    
    /**
     * @Route("/publisher/delete/{id}", name="publisher_delete")
     */
    public function deletePublisher ($id)
    {
        $publisher = $this->getDoctrine()
                          ->getRepository(Publisher::class)
                          ->find($id);
        if($publisher == null) {
            $this->addFlash("Error", "Invalid Publisher ID");
            return $this->redirectToRoute("publisher_list");
        }
        $manager = $this->getDoctrine()
                        ->getManager();
        $manager->remove($publisher);
        $manager->flush();
        $this->addFlash("Info", "Publisher has been deleted");    
        return $this->redirectToRoute("publisher_list");
    }

    /**
     * @Route("/publisher/create", name="publisher_create")
     */
    public function createPublisher (Request $request)
    {
        $publisher = new Publisher();
        $form = $this->createForm(PublisherType::class,$publisher);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {   
            $uploadedFile = $form['Image'] -> getData();
            if ($uploadedFile != null)
            {
                $image = $publisher->getImage();
                $fileName = md5(uniqid());
                $fileExtension = $image->guessExtension();
                $imageName = $fileName . '.' . $fileExtension;
                try{
                    $image->move (
                        $this->getParameter('phone_image'), $imageName
                    );
                } catch (FileException $e) {
                    throwException($e);
                }
                $publisher->setImage($imageName);
            }
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($publisher);
            $manager->flush();

            $this->addFlash("Info", "Publisher has been added!");
            return $this->redirectToRoute("publisher_list");
        }
        return $this->render(
            "publisher/create.html.twig",
            [
                "form" => $form->createView()
            ]
        );
    }

    /**
     * @Route("/publisher/update/{id}", name="publisher_update")
     */
    public function updatePublisher (Request $request, $id)
    {
        $publisher = $this->getDoctrine()
                          ->getRepository(Publisher::class)
                          ->find($id);
        $form = $this->createForm(PublisherType::class,$publisher);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {   
            $uploadedFile = $form['Image'] -> getData();
            if ($uploadedFile != null)
            {
                $image = $publisher->getImage();
                $fileName = md5(uniqid());
                $fileExtension = $image->guessExtension();
                $imageName = $fileName . '.' . $fileExtension;
                try{
                    $image->move (
                        $this->getParameter('phone_image'), $imageName
                    );
                } catch (FileException $e) {
                    throwException($e);
                }
                $publisher->setImage($imageName);
            }
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($publisher);
            $manager->flush();

            $this->addFlash("Info", "Publisher has been updated!");
            return $this->redirectToRoute("publisher_list");
        }
        return $this->render(
            "publisher/update.html.twig",
            [
                "form" => $form->createView()
            ]
        );
    }
   
}

templates/publisher/create.html.twig
{% extends "base.html.twig" %}
{% block title %} Create a new Publisher {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Create Publisher </h2>
        <div class="col-md-5">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.CompanyName) }}
                    {{ form_widget (form.CompanyName, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Country) }}
                    {{ form_widget (form.Country, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Founded) }}
                    {{ form_widget (form.Founded, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Image) }}
                    {{ form_widget (form.Image, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group text-center mt-3">
                    <button class="btn btn-success">Create</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}

templates/publisher/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publisher Detail{% endblock %}

{% block body %}

<div class="container mt-3">
    <table class = "table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Publisher ID</th>
                <th scope="col">Company Name</th>
                <th scope="col">Country</th>
                <th scope="col">Founded Year</th>
                <th scope="col">Image</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row">{{ publisher.id}}</td>
                <td scope="row">{{ publisher.companyname}}</td>
                <td scope="row">{{ publisher.country}}</td>
                <td scope="row">{{ publisher.founded}}</td>
                <td scope="row">
                    {% if publisher.Image != null %}
                        <img src="{{asset ('images/products/' ~ publisher.image)}}" width="100px" height="120px">
                    {% else %}
                        <img src="{{asset ('images/products/X.png')}}" width="100px" height="120px">
                    {% endif %}
                </td>              
                <td scope="row">
                    <a class="btn btn-success" href="{{ path ('publisher_update', {'id': publisher.id} )}}">Update</a>
                    <a class="btn btn-success" href="{{ path ('publisher_delete', {'id': publisher.id}) }}" onclick="return confirm('This publisher will be deleted!')">Delete</a>
            </tr>
        </tbody>
</div>
{% endblock %}

templates/publisher/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Publisher Information{% endblock %}

{% block body %}

<div class="container mt-3">
    {% for flash in app.flashes("Info") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Error") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>
<div class="container-fluid">
<a class="btn btn-success" href="{{ path ( 'publisher_create' ) }}">Create New Publisher</a>
<table class = "table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">Publisher ID</th>
            <th scope="col">Company Name</th>
            <th scope="col">Quantity</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for publisher in publishers %}
        <tr>
            <td scope="row">{{ publisher.id}}</td>
            <td scope="row">{{ publisher.companyname}}</td>
            <td scope="row">{{ publisher.phones|length }}</td>
            <td scope="row">
                <a class="btn btn-success" href="{{ path('publisher_detail', {'id': publisher.id} )}}">Detail</a>
                <a class="btn btn-success" href="{{ path('publisher_update', {'id': publisher.id} )}}">Update</a>
                <a class="btn btn-success" href="{{ path('publisher_delete', {'id': publisher.id} )}}"
                onclick="return confirm('This publisher will be deleted!')"
                >Delete</a>
        </tr>
    {% endfor %}

    
    </tbody>
</div>
{% endblock %}

templates/publisher/update.html.twig
{% extends "base.html.twig" %}
{% block title %} Update Publisher {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Update Publisher </h2>
        <div class="col-md-5">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.CompanyName) }}
                    {{ form_widget (form.CompanyName, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Country) }}
                    {{ form_widget (form.Country, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Founded) }}
                    {{ form_widget (form.Founded, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Image) }}
                    {{ form_widget (form.Image, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group text-center mt-3">
                    <button class="btn btn-success">Update</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}