src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * 
     * @ORM\ManyToMany(targetEntity=Phone::class, inversedBy="Quantity", orphanRemoval=true)
     * @ORM\JoinTable(name="order_phone")
     */
    private $Phone;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Quantity;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $GuestName;

    public function __construct()
    {
        $this->Phone = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Phone[]
     */
    public function getPhone(): Collection
    {
        return $this->Phone;
    }

    public function addPhone(Phone $phone): self
    {
        if (!$this->Phone->contains($phone)) {
            $this->Phone[] = $phone;
        }

        return $this;
    }

    public function removePhone(Phone $phone): self
    {
        $this->Phone->removeElement($phone);

        return $this;
    }

    public function getQuantity(): ?string
    {
        return $this->Quantity;
    }

    public function setQuantity(string $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getGuestName(): ?string
    {
        return $this->GuestName;
    }

    public function setGuestName(string $GuestName): self
    {
        $this->GuestName = $GuestName;

        return $this;
    }
    public function __toString() { return $this->PhoneName; }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use App\Entity\Phone;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Phone', EntityType::class, [
            'class' => Phone::class,
            'choice_label' => 'PhoneName',
            'multiple' => true,
            'expanded' => false
            ])
            ->add('Quantity')
            ->add('GuestName');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrderController extends AbstractController
{
    /**
     * @Route("/order", name="order_list")
     */
    public function listOrder () {
        $orders = $this->getDoctrine()
                        ->getRepository(Order::class)
                        ->findAll();
    
        return $this->render(
                        "order/index.html.twig",
                        [
                            'orders' => $orders
                        ]
                     );
    }

    /**
     * @Route("/order/detail/{id}", name="order_detail")
     */
    public function detailOrder ($id) {
        $order = $this->getDoctrine()
                       ->getRepository(Order::class)
                       ->find($id);

        if ($order == null) {
            $this->addFlash("Error", "Order ID in invalid");
            return $this->redirectToRoute("order_list");
        }

        return $this->render(
                        "order/detail.html.twig",
                        [
                          'order' => $order
                        ]
        );
    }

    
    /**
     * @Route("/order/delete/{id}", name="order_delete")
     */
    public function deleteOrder ($id)
    {
        $order = $this->getDoctrine()
                          ->getRepository(Order::class)
                          ->find($id);
        if($order == null) {
            $this->addFlash("Error", "Invalid Order ID");
            return $this->redirectToRoute("order_list");
        }
        $manager = $this->getDoctrine()
                        ->getManager();
        $manager->remove($order);
        $manager->flush();
        $this->addFlash("Info", "Order has been deleted");    
        return $this->redirectToRoute("order_list");
    }

    /**
     * @Route("/order/create", name="order_create")
     */
    public function createOrder (Request $request)
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class,$order);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            $manager = $this->getDoctrine()
                            ->getManager();
            $manager->persist($order);
            $manager->flush();

            $this->addFlash("Info", "Order has been added!");
            return $this->redirectToRoute("order_list");
        }
        return $this->render(
            "order/create.html.twig",
            [
                "form" => $form->createView()
            ]
        );
    }
}

templates/order/create.html.twig
{% extends "base.html.twig" %}
{% block title %} Add an Order {% endblock %}

{% block body %}
    <div class="container-fluid mt-3"> 
        <h2 class="text-center mt-3"> Create Order </h2>
        <div class="col-md-8">         </div>
            {{ form_start (form) }}
                <div class="form-group">
                    {{ form_label (form.Phone) }}
                    {{ form_widget (form.Phone, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.Quantity) }}
                    {{ form_widget (form.Quantity, {'attr': {'class': 'form-control'} }) }}
                </div>
                <div class="form-group">
                    {{ form_label (form.GuestName) }}
                    {{ form_widget (form.GuestName, {'attr': {'class': 'form-control'} }) }}
                </div>

                <div class="form-group text-center mt-3">
                    <button class="btn btn-success">Create</button>
                </div>
            {{ form_end (form) }}
    </div>
{% endblock %}

templates/order/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Phone Detail{% endblock %}

{% block body %}

<div class="container mt-3">
    <table class = "table table-dark table-striped">
        <thead>
            <tr>
                <th scope="col">Order ID</th>
                <th scope="col">Phone Name</th>
                <th scope="col">Quantity</th>
                <th scope="col">GuestName</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td scope="row">{{ order.id}}</td>
                <td scope="row">
                {% for a in order.phone %}
                  <a href="{{ path('phone_detail', {'id' : a.id }) }}">
                       {{ a.phonename }}
                  </a>
                  <br>
                {% endfor %}
                </td>
                <td scope="row">{{ order.quantity}}</td>
                <td scope="row">{{ order.guestname}}</td>              
                <td scope="row">
                    <a class="btn btn-success" href="{{ path ('order_delete', {'id': order.id}) }}"onclick="return confirm('This publisher will be deleted!')">Delete</a>
            </tr>
        </tbody>
</div>
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order Information{% endblock %}

{% block body %}

<div class="container mt-3">
    {% for flash in app.flashes("Info") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Error") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>
<div class="container-fluid">
<a class="btn btn-success" href="{{ path ( 'order_create' ) }}">Add New Order</a>
<table class = "table table-dark table-striped">
    <thead>
        <tr>
            <th scope="col">Order ID</th>
            <th scope="col">Guest Name</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for order in orders %}
        <tr>
            <td scope="row">{{ order.id}}</td>
            <td scope="row">{{ order.guestname}}</td>
            <td scope="row">
                <a class="btn btn-success" href="{{ path('order_detail', {'id': order.id} )}}">Detail</a>
                <a class="btn btn-success" href="{{ path('order_delete', {'id': order.id} )}}"
                onclick="return confirm('This publisher will be deleted!')">Delete</a>
        </tr>
    </tbody>
    {% endfor %}
</div>
{% endblock %}